spring.application.name=approval

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=apprit
spring.datasource.password=apprit123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.data.mongodb.uri=mongodb://localhost:27017/approvaldb

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=./uploads

jwt.secret=approvalSecretKeyApprovalSecretKey123456
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

# Blockchain / Web3j
web3j.clientAddress=http://localhost:8545
web3j.contractAddress=0x5FC8d32690cc91D4c39d9d3abcBD16989F875707
web3j.privateKey=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
